In [ ]:
import pandas as pd

file_path = '/content/Fangraphs Data for DATA 606 - Batting 2016-2025.csv'
df = pd.read_csv(file_path)

# Display the first 5 rows and the column names to verify
print(df.head())
print(df.columns)

   Season                Name Team   PA       BB%        K%      BB/K  \
0    2024      Corbin Carroll  ARI  684  0.106725  0.190058  0.561538
1    2025      Corbin Carroll  ARI  642  0.104361  0.238318  0.437908
2    2018  Dee Strange-Gordon  SEA  588  0.015306  0.136054  0.112500
3    2025     Elly De La Cruz  CIN  699  0.095851  0.258941  0.370166
4    2023    Gunnar Henderson  BAL  622  0.090032  0.255627  0.352201

        AVG       OBP       SLG  ...         LA  Barrels   Barrel%  HardHit  \
0  0.230900  0.321586  0.427844  ...  11.732181       34  0.072187      192
1  0.258865  0.342679  0.540780  ...  16.697337       60  0.144578      207
2  0.267986  0.288428  0.348921  ...   5.764835        1  0.002041       61
3  0.263911  0.336195  0.440382  ...   7.636771       46  0.102450      198
4  0.255357  0.324759  0.489286  ...  11.431762       46  0.113861      210

   HardHit%      xSLG     xwOBA           NameASCII  PlayerId  MLBAMID
0  0.407643  0.402842  0.329690      Corbin Carroll     25878   682998
1  0.498795  0.528913  0.371979      Corbin Carroll     25878   682998
2  0.124490  0.325112  0.271688  Dee Strange-Gordon      8203   543829
3  0.440980  0.423655  0.321530     Elly De La Cruz     26668   682829
4  0.519802  0.479309  0.346135    Gunnar Henderson     26289   683002

[5 rows x 60 columns]
Index(['Season', 'Name', 'Team', 'PA', 'BB%', 'K%', 'BB/K', 'AVG', 'OBP',
       'SLG', 'OPS', 'ISO', 'Spd', 'BABIP', 'UBR', 'wGDP', 'XBR', 'wSB', 'wRC',
       'wRAA', 'wOBA', 'wRC+', 'Age', 'G', 'AB', 'H', 'HR', 'R', 'RBI', 'BB',
       'IBB', 'SB', 'Bat', 'Fld', 'Rep', 'Pos', 'WAR', 'WPA', 'RE24', 'REW',
       'pLI', 'WPA/LI', 'Clutch', 'BsR', 'Def', 'Off', 'Lg', 'OBP+', 'ISO+',
       'BABIP+', 'LA', 'Barrels', 'Barrel%', 'HardHit', 'HardHit%', 'xSLG',
       'xwOBA', 'NameASCII', 'PlayerId', 'MLBAMID'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5137 entries, 0 to 5136
Data columns (total 60 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Season     5137 non-null   int64
 1   Name       5137 non-null   object
 2   Team       5137 non-null   object
 3   PA         5137 non-null   int64
 4   BB%        5137 non-null   float64
 5   K%         5137 non-null   float64
 6   BB/K       5137 non-null   float64
 7   AVG        5137 non-null   float64
 8   OBP        5137 non-null   float64
 9   SLG        5137 non-null   float64
 10  OPS        5137 non-null   float64
 11  ISO        5137 non-null   float64
 12  Spd        5137 non-null   float64
 13  BABIP      5137 non-null   float64
 14  UBR        4470 non-null   float64
 15  wGDP       4470 non-null   float64
 16  XBR        5137 non-null   float64
 17  wSB        5137 non-null   float64
 18  wRC        5137 non-null   float64
 19  wRAA       5137 non-null   float64
 20  wOBA       5137 non-null   float64
 21  wRC+       5137 non-null   float64
 22  Age        5137 non-null   int64
 23  G          5137 non-null   int64
 24  AB         5137 non-null   int64
 25  H          5137 non-null   int64
 26  HR         5137 non-null   int64
 27  R          5137 non-null   int64
 28  RBI        5137 non-null   int64
 29  BB         5137 non-null   int64
 30  IBB        5137 non-null   int64
 31  SB         5137 non-null   int64
 32  Bat        5137 non-null   float64
 33  Fld        5106 non-null   float64
 34  Rep        5137 non-null   float64
 35  Pos        5137 non-null   float64
 36  WAR        5137 non-null   float64
 37  WPA        5137 non-null   float64
 38  RE24       5137 non-null   float64
 39  REW        5137 non-null   float64
 40  pLI        5137 non-null   float64
 41  WPA/LI     5137 non-null   float64
 42  Clutch     5137 non-null   float64
 43  BsR        5137 non-null   float64
 44  Def        5137 non-null   float64
 45  Off        5137 non-null   float64
 46  Lg         5137 non-null   float64
 47  OBP+       5137 non-null   float64
 48  ISO+       5137 non-null   float64
 49  BABIP+     5137 non-null   float64
 50  LA         5137 non-null   float64
 51  Barrels    5137 non-null   int64
 52  Barrel%    5137 non-null   float64
 53  HardHit    5137 non-null   int64
 54  HardHit%   5137 non-null   float64
 55  xSLG       5137 non-null   float64
 56  xwOBA      5137 non-null   float64
 57  NameASCII  5137 non-null   object
 58  PlayerId   5137 non-null   int64
 59  MLBAMID    5137 non-null   int64
dtypes: float64(41), int64(16), object(3)
memory usage: 2.4+ MB

Let's check the null values in "Fld" first.

In [ ]:
df[df['Fld'].isnull()]

,Season,Name,Team,PA,BB%,K%,BB/K,AVG,OBP,SLG,...,LA,Barrels,Barrel%,HardHit,HardHit%,xSLG,xwOBA,NameASCII,PlayerId,MLBAMID
116,2025,Shohei Ohtani,LAD,727,0.149931,0.257221,0.582888,0.281506,0.391724,0.621931,...,14.976526,100,0.233645,250,0.584112,0.649394,0.425096,Shohei Ohtani,19755,660271
266,2023,Byron Buxton,MIN,347,0.100865,0.314121,0.321101,0.207237,0.293948,0.437500,...,20.105528,29,0.145729,91,0.457286,0.430550,0.316254,Byron Buxton,14161,621439
340,2023,Shohei Ohtani,LAA,599,0.151920,0.238731,0.636364,0.303823,0.412458,0.653924,...,13.160112,70,0.193370,193,0.533149,0.647123,0.427627,Shohei Ohtani,19755,660271
857,2018,Shohei Ohtani,LAA,367,0.100817,0.277929,0.362745,0.285276,0.360656,0.564417,...,12.269058,36,0.159292,115,0.508850,0.543575,0.381642,Shohei Ohtani,19755,660271
915,2020,Shohei Ohtani,LAA,175,0.125714,0.285714,0.440000,0.189542,0.291429,0.366013,...,9.155340,11,0.106796,44,0.427184,0.423307,0.331182,Shohei Ohtani,19755,660271
1000,2024,Shohei Ohtani,LAD,731,0.110807,0.221614,0.500000,0.309748,0.390110,0.646226,...,16.198745,103,0.213693,288,0.597510,0.672090,0.443898,Shohei Ohtani,19755,660271
1851,2022,Shohei Ohtani,LAA,666,0.108108,0.241742,0.447205,0.273038,0.355856,0.518771,...,12.096471,72,0.168224,213,0.497664,0.569288,0.386726,Shohei Ohtani,19755,660271
1855,2025,David Fry,CLE,157,0.057325,0.369427,0.155172,0.171233,0.229299,0.363014,...,22.941860,8,0.090909,35,0.397727,0.260310,0.205482,David Fry,24934,681807
2190,2016,Justin Morneau,CHW,218,0.055046,0.238532,0.230769,0.261084,0.302752,0.428571,...,9.263158,6,0.039216,55,0.359477,0.355252,0.279540,Justin Morneau,1737,408047
2415,2024,Joc Pederson,ARI,449,0.122494,0.233853,0.523810,0.275204,0.392777,0.514986,...,16.984615,34,0.125461,123,0.453875,0.489916,0.380680,Joc Pederson,11899,592626
2428,2019,Hanley Ramirez,CLE,57,0.140351,0.298246,0.470588,0.183673,0.298246,0.326531,...,6.250000,2,0.062500,14,0.437500,0.346306,0.296076,Hanley Ramirez,8001,434670
2532,2020,Khris Davis,OAK,99,0.101010,0.262626,0.384615,0.200000,0.303030,0.329412,...,18.850000,5,0.083333,19,0.316667,0.407224,0.320247,Khris Davis,9112,501981
3086,2019,Shohei Ohtani,LAA,425,0.077647,0.258824,0.300000,0.286458,0.342790,0.505208,...,6.744604,34,0.121429,131,0.467857,0.486852,0.349587,Shohei Ohtani,19755,660271
3109,2020,Giancarlo Stanton,NYY,94,0.159574,0.287234,0.555556,0.250000,0.387097,0.500000,...,8.326531,9,0.180000,25,0.500000,0.533632,0.409111,Giancarlo Stanton,4949,519317
3306,2023,Nelson Cruz,SDP,152,0.039474,0.302632,0.130435,0.244755,0.282895,0.398601,...,10.234694,9,0.091837,47,0.479592,0.421808,0.296849,Nelson Cruz,2434,443558
3617,2024,Daniel Vogelbach,TOR,79,0.113924,0.215190,0.529412,0.185714,0.278481,0.300000,...,8.019608,5,0.094340,23,0.433962,0.494663,0.368686,Daniel Vogelbach,14130,596129
4088,2020,Edwin Encarnación,CHW,181,0.088398,0.298343,0.296296,0.157233,0.250000,0.377358,...,22.830189,14,0.130841,35,0.327103,0.366075,0.277332,Edwin Encarnacion,2151,429665
4157,2020,Nelson Cruz,MIN,214,0.116822,0.271028,0.431034,0.302703,0.397196,0.594595,...,9.400000,19,0.149606,60,0.472441,0.545475,0.383333,Nelson Cruz,2434,443558
4268,2022,Nelson Cruz,WSN,507,0.096647,0.234714,0.411765,0.234375,0.313492,0.337054,...,7.179331,31,0.092537,153,0.456716,0.410084,0.322031,Nelson Cruz,2434,443558
4473,2024,J.D. Martinez,NYM,495,0.098990,0.284848,0.347518,0.235023,0.319756,0.405530,...,14.360544,44,0.147157,136,0.454850,0.480027,0.352630,J.D. Martinez,6184,502110
4553,2016,Alex Rodriguez,NYY,243,0.057613,0.275720,0.208955,0.200000,0.246914,0.351111,...,10.725000,12,0.074534,62,0.385093,0.395129,0.287494,Alex Rodriguez,1274,121347
4587,2025,Marcell Ozuna,ATL,592,0.158784,0.243243,0.652778,0.232033,0.355330,0.400411,...,14.129310,40,0.113960,156,0.444444,0.447559,0.353528,Marcell Ozuna,10324,542303
4627,2019,Nelson Cruz,MIN,521,0.107486,0.251440,0.427481,0.310573,0.392308,0.638767,...,13.134969,65,0.198777,168,0.513761,0.637938,0.415964,Nelson Cruz,2434,443558
4835,2022,J.D. Martinez,BOS,596,0.087248,0.243289,0.358621,0.273921,0.341176,0.448405,...,14.135204,49,0.124365,164,0.416244,0.486057,0.351824,J.D. Martinez,6184,502110
4864,2023,Daniel Vogelbach,NYM,319,0.131661,0.253918,0.518519,0.232727,0.338558,0.403636,...,14.489691,18,0.092784,97,0.500000,0.407201,0.324935,Daniel Vogelbach,14130,596129
4919,2020,Miguel Cabrera,DET,231,0.103896,0.220779,0.470588,0.250000,0.329004,0.416667,...,12.098039,15,0.096774,77,0.496774,0.519634,0.378606,Miguel Cabrera,1744,408234
5024,2024,Marcell Ozuna,ATL,688,0.107558,0.247093,0.435294,0.301980,0.378457,0.546205,...,14.422374,68,0.154195,235,0.532880,0.582661,0.404057,Marcell Ozuna,10324,542303
5038,2018,Victor Martinez,DET,508,0.062992,0.096457,0.653061,0.250535,0.297244,0.353319,...,14.096927,20,0.047059,130,0.305882,0.406185,0.313275,Victor Martinez,393,400121
5044,2022,Miguel Cabrera,DET,433,0.064665,0.233256,0.277228,0.254408,0.304850,0.317380,...,5.016722,14,0.046512,115,0.382060,0.340325,0.277235,Miguel Cabrera,1744,408234
5055,2024,Giancarlo Stanton,NYY,459,0.082789,0.311547,0.265734,0.232614,0.298475,0.474820,...,14.754579,57,0.206522,152,0.550725,0.520352,0.353612,Giancarlo Stanton,4949,519317
5074,2017,Victor Martinez,DET,435,0.082759,0.144828,0.571429,0.255102,0.324138,0.372449,...,13.230061,18,0.054381,114,0.344411,0.440987,0.334292,Victor Martinez,393,400121

These are all players with limited time in the field, due to being Designated Hitters. As such, we should impute a 0 for the nulls.

In [ ]:
df['Fld'] = df['Fld'].fillna(0)

# Display the first few rows to verify the imputation
print(df[df['Fld'] == 0].head())

     Season           Name Team   PA       BB%        K%      BB/K       AVG  \
116    2025  Shohei Ohtani  LAD  727  0.149931  0.257221  0.582888  0.281506
266    2023   Byron Buxton  MIN  347  0.100865  0.314121  0.321101  0.207237
340    2023  Shohei Ohtani  LAA  599  0.151920  0.238731  0.636364  0.303823
857    2018  Shohei Ohtani  LAA  367  0.100817  0.277929  0.362745  0.285276
915    2020  Shohei Ohtani  LAA  175  0.125714  0.285714  0.440000  0.189542

          OBP       SLG  ...         LA  Barrels   Barrel%  HardHit  HardHit%  \
116  0.391724  0.621931  ...  14.976526      100  0.233645      250  0.584112
266  0.293948  0.437500  ...  20.105528       29  0.145729       91  0.457286
340  0.412458  0.653924  ...  13.160112       70  0.193370      193  0.533149
857  0.360656  0.564417  ...  12.269058       36  0.159292      115  0.508850
915  0.291429  0.366013  ...   9.155340       11  0.106796       44  0.427184

         xSLG     xwOBA      NameASCII  PlayerId  MLBAMID
116  0.649394  0.425096  Shohei Ohtani     19755   660271
266  0.430550  0.316254   Byron Buxton     14161   621439
340  0.647123  0.427627  Shohei Ohtani     19755   660271
857  0.543575  0.381642  Shohei Ohtani     19755   660271
915  0.423307  0.331182  Shohei Ohtani     19755   660271

[5 rows x 60 columns]

The only other columns with null values are "UBR" and "wGDP". These are both related to a player's baserunning ability. Since "XBR" is another metric for baserunning ability, and has no null values, we can safely drop these two columns.

In [ ]:
df = df.drop(columns=['UBR', 'wGDP'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5137 entries, 0 to 5136
Data columns (total 58 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Season     5137 non-null   int64
 1   Name       5137 non-null   object
 2   Team       5137 non-null   object
 3   PA         5137 non-null   int64
 4   BB%        5137 non-null   float64
 5   K%         5137 non-null   float64
 6   BB/K       5137 non-null   float64
 7   AVG        5137 non-null   float64
 8   OBP        5137 non-null   float64
 9   SLG        5137 non-null   float64
 10  OPS        5137 non-null   float64
 11  ISO        5137 non-null   float64
 12  Spd        5137 non-null   float64
 13  BABIP      5137 non-null   float64
 14  XBR        5137 non-null   float64
 15  wSB        5137 non-null   float64
 16  wRC        5137 non-null   float64
 17  wRAA       5137 non-null   float64
 18  wOBA       5137 non-null   float64
 19  wRC+       5137 non-null   float64
 20  Age        5137 non-null   int64
 21  G          5137 non-null   int64
 22  AB         5137 non-null   int64
 23  H          5137 non-null   int64
 24  HR         5137 non-null   int64
 25  R          5137 non-null   int64
 26  RBI        5137 non-null   int64
 27  BB         5137 non-null   int64
 28  IBB        5137 non-null   int64
 29  SB         5137 non-null   int64
 30  Bat        5137 non-null   float64
 31  Fld        5137 non-null   float64
 32  Rep        5137 non-null   float64
 33  Pos        5137 non-null   float64
 34  WAR        5137 non-null   float64
 35  WPA        5137 non-null   float64
 36  RE24       5137 non-null   float64
 37  REW        5137 non-null   float64
 38  pLI        5137 non-null   float64
 39  WPA/LI     5137 non-null   float64
 40  Clutch     5137 non-null   float64
 41  BsR        5137 non-null   float64
 42  Def        5137 non-null   float64
 43  Off        5137 non-null   float64
 44  Lg         5137 non-null   float64
 45  OBP+       5137 non-null   float64
 46  ISO+       5137 non-null   float64
 47  BABIP+     5137 non-null   float64
 48  LA         5137 non-null   float64
 49  Barrels    5137 non-null   int64
 50  Barrel%    5137 non-null   float64
 51  HardHit    5137 non-null   int64
 52  HardHit%   5137 non-null   float64
 53  xSLG       5137 non-null   float64
 54  xwOBA      5137 non-null   float64
 55  NameASCII  5137 non-null   object
 56  PlayerId   5137 non-null   int64
 57  MLBAMID    5137 non-null   int64
dtypes: float64(39), int64(16), object(3)
memory usage: 2.3+ MB

We have removed all the null values from the dataset. We can now sort it. Let's sort by player and then year.

In [ ]:
df_sorted = df.sort_values(by=['PlayerId', 'Season'])
print(df_sorted.head())

      Season             Name   Team   PA       BB%        K%      BB/K  \
5136    2016  Victor Martinez    DET  610  0.081967  0.147541  0.555556
5074    2017  Victor Martinez    DET  435  0.082759  0.144828  0.571429
5038    2018  Victor Martinez    DET  508  0.062992  0.096457  0.653061
3475    2016       Juan Uribe    CLE  259  0.057915  0.189189  0.306122
4937    2016   Carlos Beltrán  - - -  593  0.059022  0.170320  0.346535

           AVG       OBP       SLG  ...         LA  Barrels   Barrel%  \
5136  0.289331  0.350820  0.475588  ...  15.467532       39  0.083691
5074  0.255102  0.324138  0.372449  ...  13.230061       18  0.054381
5038  0.250535  0.297244  0.353319  ...  14.096927       20  0.047059
3475  0.205882  0.258687  0.331933  ...  10.052083       14  0.072917
4937  0.295290  0.337268  0.512681  ...  12.512249       31  0.068132

      HardHit  HardHit%      xSLG     xwOBA        NameASCII  PlayerId  \
5136      195  0.418455  0.505022  0.362782  Victor Martinez       393
5074      114  0.344411  0.440987  0.334292  Victor Martinez       393
5038      130  0.305882  0.406185  0.313275  Victor Martinez       393
3475       72  0.375000  0.419189  0.323160       Juan Uribe       454
4937      175  0.384615  0.434651  0.320895   Carlos Beltran       589

      MLBAMID
5136   400121
5074   400121
5038   400121
3475   346874
4937   136860

[5 rows x 58 columns]

In [ ]:
df_sorted.head()

,Season,Name,Team,PA,BB%,K%,BB/K,AVG,OBP,SLG,...,LA,Barrels,Barrel%,HardHit,HardHit%,xSLG,xwOBA,NameASCII,PlayerId,MLBAMID
5136,2016,Victor Martinez,DET,610,0.081967,0.147541,0.555556,0.289331,0.350820,0.475588,...,15.467532,39,0.083691,195,0.418455,0.505022,0.362782,Victor Martinez,393,400121
5074,2017,Victor Martinez,DET,435,0.082759,0.144828,0.571429,0.255102,0.324138,0.372449,...,13.230061,18,0.054381,114,0.344411,0.440987,0.334292,Victor Martinez,393,400121
5038,2018,Victor Martinez,DET,508,0.062992,0.096457,0.653061,0.250535,0.297244,0.353319,...,14.096927,20,0.047059,130,0.305882,0.406185,0.313275,Victor Martinez,393,400121
3475,2016,Juan Uribe,CLE,259,0.057915,0.189189,0.306122,0.205882,0.258687,0.331933,...,10.052083,14,0.072917,72,0.375000,0.419189,0.323160,Juan Uribe,454,346874
4937,2016,Carlos Beltrán,- - -,593,0.059022,0.170320,0.346535,0.295290,0.337268,0.512681,...,12.512249,31,0.068132,175,0.384615,0.434651,0.320895,Carlos Beltran,589,136860

In [ ]:
df_sorted.to_csv('mlb_player.csv', index=False)
print('DataFrame saved to mlb_player.csv')

DataFrame saved to mlb_player.csv